server:
  port: 8001

spring:
  application:
    name: ACCOUNT-MANAGEMENT-SERVICE
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: dev
    password: dev
    schema: classpath:schema.sql
    data: classpath:data.sql
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
